### PR TITLE
updated gtsam version that gets automatically downloaded.

### PR DESCRIPTION
**Pull request by pizzoli**

### CODE REVIEW

**Comment by mwerlberger** [comment]
Is there a corresponding (release) tag? I like taking it from github but I'm not sure if we should diverge from 'stable' releases? If there are features that we can't have otherwise we don't have another option but otherwise I would prefer sticking to tagged versions.

**Comment by pizzoli** [comment]
I agree, of course. 
If I remember correctly the reason why I took this very tag is being consistent with the Multiagent Mapping. Might be outdated, it is worth a double-check.

**Comment by cfo** [comment]
yes, we should have the same as mm, otherwise we are screwed.

**Comment by pizzoli** [comment]
I checked:
- no tag is defined on asl side
- no tag on gtsam bitbucket. THe SHA refers to a commit on Oct27 2015.  There is no 'stable' release related to this SHA, nor to the pull request where this commit was merged.
  The git submodule gtsam_dev on asl has not been updated. So I don't really know why this very SHA of GTSAM is being used. 
  I suggest we merge this, so we use the automatic checkout of gtsam, and then we try to lock to a stable version just modifying the tag command in the cmake file

**Comment by mwerlberger** [comment]
sure. having the same as the mm guys might be the only way to go for now....

**Pull request merged**
